### ISSUE TITLE
Add tracking for multiple incident categories with separate timers

### ISSUE THREAD

**Issue by m-lara** [anthonyisensee/incidenttracker#8]
I added two incidents to the tracker (in this case, a "time since last meeting" and a "last time since last injury) and when I ended my meeting I wanted to restart the incident but my only option is to reset everything.

What happens if I have a meeting but no injury? I can't just reset the meeting tracker, I have to lose everything. :(

**Comment by anthonyisensee** [comment]
Verified with @m-lara that this request is to add the ability to track incidents across multiple systems/categories, including a timer for each system/category.

**Comment by anthonyisensee** [comment]
@m-lara planning to show you this in our meeting tomorrow, but this feature request has been completed via a new project called [Event Tracker](https://eventtracker.anthonyisensee.com/). Please note that I've added an "Export Data" setting to [Incident Tracker](https://incidenttracker.anthonyisensee.com/)  (and a corresponding "Import Data" setting to Event Tracker) so that you can easily migrate any data you might have already tracked in Incident Tracker to Event Tracker.
